---
# =============================================================================
# KRNEL — requirements.yml
# Para ejecutar primero crear tu entorno con uv:
#   uv venv --python 3.12
# Luego activa tu entorno virtual:
#   source .venv/bin/activate
# Posteriormente instala ansible y colecciones adicionales:
#   uv tool install ansible-core --with ansible
#   uv pip install netaddr
# Ejecuta el siguiente comando para añadirlos al PATH:
#   uv tool update-shell
# Finalmente, instala los roles y colecciones con: 
#  ansible-galaxy install -r requirements.yml
#  ansible-galaxy collection install -r requirements.yml
# =============================================================================

roles:
  - name: xanmanning.k3s
    version: "v3.6.2"

collections:
  - name: community.general
    version: ">=9.0.0"
  - name: kubernetes.core
    version: ">=5.0.0"
  - name: ansible.posix
    version: ">=1.5.0"
